### ISSUE TITLE
How do I define an action to work on the folder of the matched file?

### ISSUE THREAD

**Issue by raghur** [genotrance/ff#1]
Pretty much what it says on the title 

`ff ef -s *.json`

But when I define the action `ef` , this doesn't work

```
ef.name = "Open folder"
ef.select = "file"
ef.action = "explorer {}\\.."
```

Any tips?

**Comment by genotrance** [comment]
Given you picked a file in fzf, getting the parent directory on that might require you to invoke some script/executable that does the extraction of the parent directory and then does some action on it. Here's how you can get the parent directory use [batch](https://stackoverflow.com/questions/34942604/get-parent-directory-of-a-specific-path-in-batch-script).

Meanwhile, if you just want to use explorer, you could try: ```ef.action = "explorer /select,{}"```

This will open an explorer window on the directory of that file with that file selected. I doubt this is what you want though.

**Comment by BruceChen2017** [comment]
@genotrance how to open folder where selected file is? `ef.action = "explorer /select,{}"` just open the explorer not the folder of selected file

**Comment by genotrance** [comment]
This seems like a problem with explorer. fzf replaces {} with the file path but sets `\` to `\\` in the path so when explorer gets the value, it doesn't work. If you try the following, you can see the issue.

`explorer /select,c:\windows` <= works
`explorer /select,c:\\windows` <= fails

`fzf --bind "enter:execute(start \"\" /I explorer /select,{})+abort"` <= doesn't work since fzf uses `\\`

`fzf --bind "enter:execute(start \"\" /I cmd /k cd {})+abort"` <= works since cmd doesn't mind `\\`

You might need to use a batch file which calls explorer instead. Here's a nice round about way to do it:-

test.bat:
```batch
@echo off
set path=%1
call set "path=%%path:\\=\%%"
start explorer /select,%path%
exit
```

`ef.action = "/MIN test.bat {}"`

**Comment by BruceChen2017** [comment]
@genotrance I just found a good solution.
`ef.action = "/MIN cmd /c for %i in ({}) do explorer %~dpi"`
